### ISSUE TITLE
Validate email format upon registering candidates and voters

### ISSUE THREAD

**Issue by hugocorbucci** [agile-alliance-brazil/election#17]
Currently, voters emails (which are used to send voting tokens) are not validated.
As a consequence, when we send voting tokens, we may crash (as the postal jar we use cannot handle that).
Realistically, we shouldn't allow for candidates or voters to have emails that are not even in a valid email format.

**Comment by Kineolyan** [comment]
Hello @hugocorbucci I submitted a PR with email validation on new voters.
But I was short in email ids so there are few tested email formats. If you have some emails that already caused issues with _postal_, post them and I will check that the PR works for them.

Cheers

**Comment by hugocorbucci** [comment]
In many cases is was emails missing the `@` (like you already tested), straight up missing (like empty string) and a few like `username@gmailcom`. I commented in the PR!
Thank you very much for taking the time! Really appreciate it!
